import 'dart:convert';
import 'dart:math';
import 'package:cool_alert/cool_alert.dart';
import 'package:fluro/fluro.dart';
import 'package:flutter/material.dart';
// import 'package:flutter_flushbar/flutter_flushbar.dart';
// import 'package:flutter_flushbar/flutter_flushbar.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:d_method/d_method.dart';
import 'package:http/http.dart' as http;
import 'package:google_fonts/google_fonts.dart';
import 'package:toastification/toastification.dart';
import 'package:url_launcher/url_launcher.dart';

part 'api_request.dart';
part 'app_colors.dart';
part 'app_methods.dart';
part 'app_session.dart';
part 'constant.dart';
part 'app_theme.dart';
part 'dummy.dart';
part 'application.dart';
