name: Flutter CI/CD

on:
  push:
    branches:
      - restapi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'

    - name: Add Flutter to PATH
      run: export PATH="$PATH":"$HOME/.pub-cache/bin"

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --web-renderer
