name: Flutter CI/CD

on:
  push:
    branches:
      - restapi
  pull_request:
    branches:
      - restapi
      
permissions: write

jobs:
  
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.9'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build release project
      run: flutter build web

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/restapi'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build

# on:
#   push:
#     branches:
#       - restapi

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Flutter
#       uses: subosito/flutter-action@v2
#       with:
#         flutter-version: '3.16.9'

#     - name: Add Flutter to PATH
#       run: export PATH="$PATH":"$HOME/.pub-cache/bin"

#     - name: Install dependencies
#       run: flutter pub get

#     - name: Build web
#       run: flutter build web --web-renderer
